[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=4.0.0",
    "google-genai>=1.29.0",
    "httpx>=0.28.1",
    "openai>=1.99.6",
    "python-dotenv>=1.1.1",
    "python-telegram-bot==21.5",
]
